target 'FuTu' do

platform :ios, '8.0'
pod 'Masonry','~>1.0'
pod 'SDWebImage'
pod 'AFNetworking','~>3.0'
#pod 'FMDB','~>2.6.2'
#pod 'MBProgressHUD','~>1.0'
pod 'MJRefresh'
pod 'JSONKit'
#pod 'IQKeyboardManager'
#轮播图
pod 'SDCycleScrollView'
#播放音乐
#pod 'StreamingKit'

end
